package ec.gob.informatica.consultacontrasenaws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-07-29T12:01:02.497-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.informatica.gob.ec/ConsultaContrasenaWS", name = "BSG06_Consulta_Contrasenia")
@XmlSeeAlso({ObjectFactory.class})
public interface BSG06ConsultaContrasenia {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultarContrasena", targetNamespace = "http://www.informatica.gob.ec/ConsultaContrasenaWS", className = "ec.gob.informatica.consultacontrasenaws.ConsultarContrasena")
    @WebMethod
    @ResponseWrapper(localName = "consultarContrasenaResponse", targetNamespace = "http://www.informatica.gob.ec/ConsultaContrasenaWS", className = "ec.gob.informatica.consultacontrasenaws.ConsultarContrasenaResponse")
    public ec.gob.informatica.consultacontrasenaws.ConsultarContrasenaSalida consultarContrasena(
        @WebParam(name = "consultarContrasenaEntrada", targetNamespace = "")
        ec.gob.informatica.consultacontrasenaws.ConsultarContrasenaEntrada consultarContrasenaEntrada
    );
}
