package ec.gob.registrocivil.consultacedula;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-07-29T10:58:51.209-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ConsultarCedulaServiceService", 
                  wsdlLocation = "file:/home/anarvaez/workspace/esb-consultarCedula-service/src/main/resources/consultarCedulaService.wsdl",
                  targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula") 
public class ConsultarCedulaServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.registrocivil.gob.ec/ConsultaCedula", "ConsultarCedulaServiceService");
    public final static QName ConsultarCedulaServicePort = new QName("http://www.registrocivil.gob.ec/ConsultaCedula", "ConsultarCedulaServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/anarvaez/workspace/esb-consultarCedula-service/src/main/resources/consultarCedulaService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultarCedulaServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/anarvaez/workspace/esb-consultarCedula-service/src/main/resources/consultarCedulaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultarCedulaServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarCedulaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCedulaServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ConsultarCedulaService
     */
    @WebEndpoint(name = "ConsultarCedulaServicePort")
    public ConsultarCedulaService getConsultarCedulaServicePort() {
        return super.getPort(ConsultarCedulaServicePort, ConsultarCedulaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCedulaService
     */
    @WebEndpoint(name = "ConsultarCedulaServicePort")
    public ConsultarCedulaService getConsultarCedulaServicePort(WebServiceFeature... features) {
        return super.getPort(ConsultarCedulaServicePort, ConsultarCedulaService.class, features);
    }

}
